upload each edition under its own release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -121,42 +121,32 @@ jobs:
       - name: Install gzip
         run: sudo apt-get install -y gzip
 
+      - name: Find ISO code
+        id: find_iso_code
+        run: |
+          edition_iso=$(  jq --arg query "${{ matrix.edition_language }}" -r '.[] | select(.language == $query) | .iso' -- languages.json  )
+          if [[ -z $edition_iso ]]; then
+            echo "ERROR: can't find edition ISO" >&2
+            exit 1
+          fi
+          echo "Edition ISO $edition_iso"
+          echo "edition_iso=$edition_iso" >> "$GITHUB_OUTPUT"
+
       - name: Run auto.sh script
+        # Matrix edition is a full name (not ISO), e.g. Russian
         run: ./auto.sh "${{ matrix.edition_language }}" "?" "?"
+        env:
+          TAG_NAME: ${{ needs.prepare.outputs.tag }}_${{ steps.find_iso_code.outputs.edition_iso }}
 
       - name: Upload main dictionary files
         uses: softprops/action-gh-release@v2.2.1
         with:
-          name: ${{ needs.prepare.outputs.calver }}
-          tag_name: ${{ needs.prepare.outputs.tag }}
+          name: ${{ needs.prepare.outputs.calver }} - ${{ matrix.edition_language }} Edition
+          tag_name: ${{ needs.prepare.outputs.tag }}_${{ steps.find_iso_code.outputs.edition_iso }}
           prerelease: true
           generate_release_notes: true
           files: |
-            # exclude ipa and gloss by preventing matching suffixes:
-            data/language/**/kty-??-??.zip
-            data/language/**/kty-??-???.zip
-            data/language/**/kty-???-??.zip
-            data/language/**/kty-???-???.zip
-
-      - name: Upload ipa dictionary files
-        uses: softprops/action-gh-release@v2.2.1
-        with:
-          name: ${{ needs.prepare.outputs.calver }} ipa
-          tag_name: ${{ needs.prepare.outputs.tag }}_ipa
-          prerelease: true
-          generate_release_notes: true
-          files: |
-            data/language/**/kty-?*-?*-ipa.zip
-
-      - name: Upload gloss dictionary files
-        uses: softprops/action-gh-release@v2.2.1
-        with:
-          name: ${{ needs.prepare.outputs.calver }} gloss
-          tag_name: ${{ needs.prepare.outputs.tag }}_gloss
-          prerelease: true
-          generate_release_notes: true
-          files: |
-            data/language/**/kty-?*-?*-gloss.zip
+            data/language/**/kty-?*-?*.zip
 
       #- name: Upload index.json files
       #  uses: softprops/action-gh-release@v2.2.1
@@ -172,6 +162,11 @@ jobs:
   merge-ipa:
     needs: ["prepare", "convert"]
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      max-parallel: 18
+      matrix:
+        edition_language: ${{ fromJson(needs.prepare.outputs.edition_languages) }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -183,6 +178,17 @@ jobs:
 
       - name: Install npm dependencies
         run: npm install
+
+      - name: Find ISO code
+        id: find_iso_code
+        run: |
+          edition_iso=$(  jq --arg query "${{ matrix.edition_language }}" -r '.[] | select(.language == $query) | .iso' -- languages.json  )
+          if [[ -z $edition_iso ]]; then
+            echo "ERROR: can't find target ISO" >&2
+            exit 1
+          fi
+          echo "TARGET ISO $edition_iso"
+          echo "edition_iso=$edition_iso" >> "$GITHUB_OUTPUT"
 
       - name: Download IPA dicts
         run: |
